### ISSUE TITLE
Add new feature scroll app in 1 workspace and remove system app (window:*)

### ISSUE THREAD

**Issue by GiangTT09** [Favo02/workspaces-by-open-apps#70]
Dear dev,
- Can you remove system app with id something like: window:17, window:525, .... window:*
- I want to suggest a new feature is: when i hover mouse to specific workspace so i can scroll middle mouse to change the focus of app in this workspace.
Best Regards.

**Comment by Favo02** [comment]
Thanks for the feedback!

The _system app_ can be ignored in settings, in "Hide and ignore apps" tab, adding a simple regex like `window:*` should work. Let me know if that works.

The _scroll on workspace to change application focused_ is a cool idea, I will try to implement it in the next release! I will keep this issue updated.

**Comment by titan282** [comment]
![image](https://github.com/Favo02/workspaces-by-open-apps/assets/67032039/db072b5e-018b-431b-a88a-1e50e6037432)
(i am GiangTT09 with above question)
I use Ubuntu Wayland. I have added regex window:* but it not work so i have to use log command to log the id of system app with something like: (window:2....) and i add this id with number to settings.  I realize that if i use Ubuntu Xorg, the system app will not be show by default, but it will not be in Ubuntu Wayland. Can you fix this for Wayland or simple you can let this extentions can be hide this system app with regex "window:*" instead of the id of app.

**Comment by titan282** [comment]
![image](https://github.com/Favo02/workspaces-by-open-apps/assets/67032039/db072b5e-018b-431b-a88a-1e50e6037432)
(i am GiangTT09 with above question)
I use Ubuntu Wayland. I have added regex window:* but it not work so i have to use log command to log the id of system app with something like: (window:2....) and i add this id with number to settings (but after i add this id, the new id of system app will be created and i have to do this work again to find id and add to settings).  I realize that if i use Ubuntu Xorg, the system app will not be show by default, but it will not be in Ubuntu Wayland. Can you fix this for Wayland or simple you can let this extentions can be hide this system app with regex "window:*" instead of the id of app.

**Comment by titan282** [comment]
> Thanks for the feedback!
> 
> The _system app_ can be ignored in settings, in "Hide and ignore apps" tab, adding a simple regex like `window:*` should work. Let me know if that works.
> 
> The _scroll on workspace to change application focused_ is a cool idea, I will try to implement it in the next release! I will keep this issue updated.

![image](https://github.com/Favo02/workspaces-by-open-apps/assets/67032039/db072b5e-018b-431b-a88a-1e50e6037432)
(i am GiangTT09 with above question)
I use Ubuntu Wayland. I have added regex window:* but it not work so i have to use log command to log the id of system app with something like: (window:2....) and i add this id with number to settings (but after i add this id, the new id of system app will be created and i have to do this work again to find id and add to settings).  I realize that if i use Ubuntu Xorg, the system app will not be show by default, but it will not be in Ubuntu Wayland. Can you fix this for Wayland or simple you can let this extentions can be hide this system app with regex "window:*" instead of the id of app.

**Comment by Favo02** [comment]
The issue seems to be related with the **version of the extension** you are using. The newest versions support `window:*`.

I guess you are using _Ubuntu LTS_ with _GNOME 44_, so the extension **will not auto-update** to the newer versions for _GNOME 45_.

Installing **manually** the extension ([instructions here](https://github.com/Favo02/workspaces-by-open-apps?tab=readme-ov-file#alternative-install)) will fix the issue.

Let me know if that works.
